#ifndef CONTACTSDLL_GLOBAL_H
#define CONTACTSDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTACTSDLL_LIBRARY)
#  define CONTACTSDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTACTSDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTACTSDLL_GLOBAL_H
